# Generated by Django 4.0.4 on 2022-07-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion', '0006_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
